name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cmd1=$(ls)
          cmd2=$(pwd)
          cmd3=$(whoami)          
          echo test=<<EOF >> $GITHUB_OUTPUT
          $cmd1
          $cmd2
          $cmd3
          EOF
        id: ls
    outputs:
      ls: ${{steps.ls.outputs}}
  run:
    needs: build
    runs-on: ubuntu-latest
    env:
      TEST_ENV: ${{needs.build.outputs.ls}}
    steps:
    - run: echo "test env is $TEST_ENV"
